### DISCUSSION TITLE
Astro Theme Cactus

### DISCUSSION THREAD

**Discussion by cutbypham** [rose-pine/rose-pine-theme#97] [Show and tell]
Repo: https://github.com/thuanowa/thuanowa.com
Live preview: https://thuanowa.com/
Astro theme cactus: https://github.com/chrismwilliams/astro-theme-cactus

### [global.css](https://github.com/thuanowa/thuanowa.com/blob/main/src/styles/global.css)

```css
:root {
  color-scheme: light;
  --theme-bg: #faf4ed;
  --theme-link: #907aa9;
  --theme-text: #575279;
  --theme-accent: #d7827e;
  --theme-accent-2: #b4637a;
  --theme-quote: #ea9d34;
  --theme-menu-bg: rgb(250 250 250 / 0.85);
}

:root.dark {
  color-scheme: dark;
  --theme-bg: #191724;
  --theme-link: #c4a7e7;
  --theme-text: #e0def4;
  --theme-accent: #ebbcba;
  --theme-accent-2: #eb6f92;
  --theme-quote: #f6c177;
  --theme-menu-bg: rgb(29 31 33 / 0.85);
}
```

### [astro.config.ts](https://github.com/thuanowa/thuanowa.com/blob/main/astro.config.ts)

```js
markdown: {
  shikiConfig: {
    theme: "rose-pine-dawn",
    wrap: true,
  },
},
````
